

<div id="footer-links" class="footer-links-container" data-mage-init='{"Magento_Theme/js/accordion-widget":{}}'>
    <div class="links-list">
        <div data-role="collapsible">
            <h3 class="title" data-role="title"><?= $block->escapeHtml(__('DOOGEE')) ?></h3>
        </div>
        <ul data-role="content">
            <li><a href="#">Teardown</a></li>
            <li><a href="#">News</a></li>
            <li><a href="#">Partners</a></li>
            <li><a href="#">About us </a></li>
            <li><a href="#">Contact us</a></li>
            <li><a href="#">Terms of use</a></li>
        </ul>
    </div>

    <div class="links-list">
        <div data-role="collapsible">
            <h3 class="title" data-role="title"><?= $block->escapeHtml(__('Social')) ?></h3>
        </div>
        <ul data-role="content">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Youtube</a></li>

        </ul>
    </div>

    <div class="links-list">
        <div data-role="collapsible">
            <h3 class="title" data-role="title"><?= $block->escapeHtml(__('Service')) ?></h3>
        </div>
        <ul data-role="content">
            <li><a href="#">Compare</a></li>
            <li><a href="#">Download</a></li>
            <li><a href="#">Feedback</a></li>
            <li><a href="#">Bug Report</a></li>

        </ul>
    </div>

    <div class="links-list">
        <div data-role="collapsible">
            <h3 class="title" data-role="title"><?= $block->escapeHtml(__('Activity')) ?></h3>
        </div>
        <ul data-role="content">
            <li><a href="#">Influencers</a></li>
            <li><a href="#">Affiliate</a></li>
            <li><a href="#">Co-branding</a></li>
            <li><a href="#">Honor</a></li>
            <li><a href="#">Give away</a></li>

        </ul>
    </div>
</div>





