<div class="links-list">
    <h3 class="title">DOOGEE</h3>
    <ul>
        <li><a href="#">Teardown</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">Partners</a></li>
        <li><a href="#">About us </a></li>
        <li><a href="#">Contact us</a></li>
        <li><a href="#">Terms of use</a></li>
    </ul>
</div>

<div class="links-list">
    <h3 class="title">Social</h3>
    <ul>
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Youtube</a></li>

    </ul>
</div>

<div class="links-list">
    <h3 class="title">Service</h3>
    <ul>
        <li><a href="#">Compare</a></li>
        <li><a href="#">Download</a></li>
        <li><a href="#">Feedback</a></li>
        <li><a href="#">Bug Report</a></li>

    </ul>
</div>

<div class="links-list">
    <h3 class="title">Activity</h3>
    <ul>
        <li><a href="#">Influencers</a></li>
        <li><a href="#">Affiliate</a></li>
        <li><a href="#">Co-branding</a></li>
        <li><a href="#">Honor</a></li>
        <li><a href="#">Give away</a></li>

    </ul>
</div>

