<div class="links-icons">
<ul>
<li><a href="#"><i class="fa-brands fa-facebook fa-lg"></i></a></li>
<li><a href="#"><i class="fa-brands fa-twitter fa-lg"></i></a></li>
<li><a href="#"><i class="fa-brands fa-google-plus fa-lg"></i></a></li>
<li><a href="#"><i class="fa-brands fa-youtube fa-lg"></i></a></li>
<li><a href="#"><i class="fa-brands fa-instagram fa-lg"></i></a></li>
<li><a href="#"><i class="fa-brands fa-linkedin fa-lg" ></i></a></li>
<li><a href="#"><i class="fa-brands fa-vk fa-lg"></i></a></li>
</ul>
</div>
